import { ThemeProvider } from "@/components/ui/providers"

import { Inter } from "next/font/google";
import "@/styles/globals.css";

import { AuthStoreProvider } from "@/lib/providers/auth-store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Provides a single AuthStore instance to all child pages/components/functions */}
          <AuthStoreProvider>
            {children}
          </AuthStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
