import type { Metadata } from "next";
import "@/styles/globals.css";
import { siteConfig } from "@/site.config.ts"

import { SiteHeader } from "@/components/ui/site-header"

export const metadata: Metadata = {
  title: siteConfig.name,
  description: "Generated by create next app",
};

export default function CoachingSessionLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SiteHeader />
      <main>
        {children}
      </main>
    </>
  );
}